### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by Aboyeu** [LilZevi/AminoWallSpam#1]
![IMG_20210301_031144](https://user-images.githubusercontent.com/73722936/109458590-db8c5b80-7a3b-11eb-9833-a6c5337a27ec.jpg)

All your bots appears that same message ...

**Comment by LilZevi** [comment]
Change deviceid

чт, 4 мар. 2021 г., 07:52 Random boy <notifications@github.com>:
